### PR TITLE
Create catalog-info.yaml

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Review by DominicOram — APPROVED** [review]
Great, thank you!

**Review by noemifrisina — CHANGES_REQUESTED** [review]
Looks like tests are failing because this branch is missing some of the latests changes using the updated pmac device in `dodal`. 
Could you sync your fork and merge main please? That should fix the issue

**Review by noemifrisina — APPROVED** [review]
lgtm, thanks!

**Comment by stan-dot** [comment]
closed in favor of #113

**Pull request closed without merging**
